// Regenerate with: dart run ffigen --config ffigen.native_assets.yaml

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:fllamer/llama_dart_bridge')
library;

import 'dart:ffi' as ffi;
import '' as self;

@ffi.Native<ffi.Uint32 Function()>()
external int llama_dart_abi_version();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> llama_dart_upstream_commit();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> llama_dart_build_flags();

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int32)>()
external ffi.Pointer<ffi.Char> llama_dart_model_file_type_name(int ftype);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> llama_dart_multimodal_marker();

@ffi.Native<ffi.UnsignedInt Function(ffi.Uint32)>()
external int llama_dart_log_set_level(int minimum_level);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<llama_dart_buffer>,
  )
>()
external int llama_dart_log_next(
  ffi.Pointer<ffi.Uint32> out_level,
  ffi.Pointer<llama_dart_buffer> out_message,
);

@ffi.Native<ffi.UnsignedInt Function()>()
external int llama_dart_backend_init();

@ffi.Native<ffi.UnsignedInt Function()>()
external int llama_dart_backend_free();

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<llama_dart_capabilities>)>()
external int llama_dart_get_capabilities(
  ffi.Pointer<llama_dart_capabilities> out_capabilities,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model_load_config>,
    ffi.Pointer<ffi.Pointer<llama_dart_model>>,
  )
>()
external int llama_dart_model_load(
  ffi.Pointer<llama_dart_model_load_config> config,
  ffi.Pointer<ffi.Pointer<llama_dart_model>> out_model,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_dart_model>)>()
external void llama_dart_model_free(ffi.Pointer<llama_dart_model> model);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Pointer<llama_dart_model_info>,
  )
>()
external int llama_dart_model_get_info(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<llama_dart_model_info> out_info,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int llama_dart_model_get_description(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<ffi.Char> buffer,
  int buffer_size,
  ffi.Pointer<ffi.Size> out_size,
);

@ffi.Native<
  ffi.UnsignedInt Function(ffi.Pointer<llama_dart_model>, ffi.Pointer<ffi.Size>)
>()
external int llama_dart_model_metadata_count(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<ffi.Size> out_count,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int llama_dart_model_metadata_get(
  ffi.Pointer<llama_dart_model> model,
  int index,
  ffi.Pointer<ffi.Char> key_buffer,
  int key_buffer_size,
  ffi.Pointer<ffi.Size> out_key_size,
  ffi.Pointer<ffi.Char> value_buffer,
  int value_buffer_size,
  ffi.Pointer<ffi.Size> out_value_size,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Pointer<llama_dart_buffer>,
  )
>()
external int llama_dart_model_get_chat_template(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<llama_dart_buffer> out_template,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Int32>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
    ffi.Uint8,
    ffi.Uint8,
  )
>()
external int llama_dart_model_tokenize(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<ffi.Uint8> text_data,
  int text_size,
  ffi.Pointer<ffi.Int32> tokens,
  int tokens_capacity,
  ffi.Pointer<ffi.Size> out_token_count,
  int add_special,
  int parse_special,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Pointer<ffi.Int32>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
    ffi.Uint8,
    ffi.Uint8,
  )
>()
external int llama_dart_model_detokenize(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<ffi.Int32> tokens,
  int token_count,
  ffi.Pointer<ffi.Uint8> text_data,
  int text_capacity,
  ffi.Pointer<ffi.Size> out_text_size,
  int remove_special,
  int unparse_special,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Pointer<llama_dart_chat_message>,
    ffi.Size,
    ffi.Uint8,
    ffi.Pointer<llama_dart_buffer>,
  )
>()
external int llama_dart_model_apply_chat_template(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<llama_dart_chat_message> messages,
  int message_count,
  int add_assistant_prompt,
  ffi.Pointer<llama_dart_buffer> out_prompt,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Pointer<llama_dart_chat_template_capabilities>,
  )
>()
external int llama_dart_model_get_chat_template_capabilities(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<llama_dart_chat_template_capabilities> out_capabilities,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<llama_dart_buffer>,
  )
>()
external int llama_dart_model_create_chat_plan(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<ffi.Uint8> request_data,
  int request_size,
  ffi.Pointer<llama_dart_buffer> out_plan,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<llama_dart_buffer>,
  )
>()
external int llama_dart_chat_parse_output(
  ffi.Pointer<ffi.Uint8> plan_data,
  int plan_size,
  ffi.Pointer<ffi.Uint8> output_data,
  int output_size,
  ffi.Pointer<llama_dart_buffer> out_message_json,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<llama_dart_buffer>,
  )
>()
external int llama_dart_json_schema_to_grammar(
  ffi.Pointer<ffi.Uint8> schema_data,
  int schema_size,
  ffi.Pointer<llama_dart_buffer> out_grammar,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Pointer<llama_dart_context_config>,
    ffi.Pointer<ffi.Pointer<llama_dart_context>>,
  )
>()
external int llama_dart_context_create(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<llama_dart_context_config> config,
  ffi.Pointer<ffi.Pointer<llama_dart_context>> out_context,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_dart_context>)>()
external void llama_dart_context_free(ffi.Pointer<llama_dart_context> context);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<llama_dart_context>)>()
external int llama_dart_context_reset(ffi.Pointer<llama_dart_context> context);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<llama_dart_context>)>()
external int llama_dart_context_warm_up(
  ffi.Pointer<llama_dart_context> context,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<llama_dart_context>)>()
external int llama_dart_context_cancel(ffi.Pointer<llama_dart_context> context);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_context>,
    ffi.Pointer<llama_dart_context_info>,
  )
>()
external int llama_dart_context_get_info(
  ffi.Pointer<llama_dart_context> context,
  ffi.Pointer<llama_dart_context_info> out_info,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_context>,
    ffi.Pointer<llama_dart_buffer>,
  )
>()
external int llama_dart_context_state_get(
  ffi.Pointer<llama_dart_context> context,
  ffi.Pointer<llama_dart_buffer> out_state,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_context>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int llama_dart_context_state_set(
  ffi.Pointer<llama_dart_context> context,
  ffi.Pointer<ffi.Uint8> state_data,
  int state_size,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_context>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint32>,
  )
>()
external int llama_dart_context_shift(
  ffi.Pointer<llama_dart_context> context,
  int keep_tokens,
  int discard_tokens,
  ffi.Pointer<ffi.Uint32> out_discarded_tokens,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_context>,
    ffi.Pointer<llama_dart_completion_config>,
    ffi.Pointer<llama_dart_buffer>,
    ffi.Pointer<llama_dart_completion_stats>,
  )
>()
external int llama_dart_context_complete(
  ffi.Pointer<llama_dart_context> context,
  ffi.Pointer<llama_dart_completion_config> config,
  ffi.Pointer<llama_dart_buffer> out_text,
  ffi.Pointer<llama_dart_completion_stats> out_stats,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_context>,
    ffi.Pointer<llama_dart_completion_config>,
    ffi.Pointer<ffi.Pointer<llama_dart_generation>>,
  )
>()
external int llama_dart_generation_start(
  ffi.Pointer<llama_dart_context> context,
  ffi.Pointer<llama_dart_completion_config> config,
  ffi.Pointer<ffi.Pointer<llama_dart_generation>> out_generation,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_generation>,
    ffi.Pointer<llama_dart_buffer>,
    ffi.Pointer<llama_dart_completion_stats>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external int llama_dart_generation_next(
  ffi.Pointer<llama_dart_generation> generation,
  ffi.Pointer<llama_dart_buffer> out_text,
  ffi.Pointer<llama_dart_completion_stats> out_stats,
  ffi.Pointer<ffi.Uint8> out_done,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_dart_generation>)>()
external void llama_dart_generation_free(
  ffi.Pointer<llama_dart_generation> generation,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_context>,
    ffi.Pointer<llama_dart_embedding_config>,
    ffi.Pointer<llama_dart_float_buffer>,
  )
>()
external int llama_dart_context_embed(
  ffi.Pointer<llama_dart_context> context,
  ffi.Pointer<llama_dart_embedding_config> config,
  ffi.Pointer<llama_dart_float_buffer> out_embedding,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_context>,
    ffi.Pointer<llama_dart_rerank_config>,
    ffi.Pointer<ffi.Float>,
  )
>()
external int llama_dart_context_rerank(
  ffi.Pointer<llama_dart_context> context,
  ffi.Pointer<llama_dart_rerank_config> config,
  ffi.Pointer<ffi.Float> out_score,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_model>,
    ffi.Pointer<llama_dart_lora_load_config>,
    ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>>,
  )
>()
external int llama_dart_lora_load(
  ffi.Pointer<llama_dart_model> model,
  ffi.Pointer<llama_dart_lora_load_config> config,
  ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>> out_adapter,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_dart_lora_adapter>)>()
external void llama_dart_lora_free(
  ffi.Pointer<llama_dart_lora_adapter> adapter,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<llama_dart_context>,
    ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>>,
    ffi.Pointer<ffi.Float>,
    ffi.Size,
  )
>()
external int llama_dart_context_set_lora_adapters(
  ffi.Pointer<llama_dart_context> context,
  ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>> adapters,
  ffi.Pointer<ffi.Float> scales,
  int adapter_count,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>)>()
external void llama_dart_buffer_free(ffi.Pointer<ffi.Uint8> data);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Float>)>()
external void llama_dart_float_buffer_free(ffi.Pointer<ffi.Float> data);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> llama_dart_last_error_message();

@ffi.Native<ffi.Void Function()>()
external void llama_dart_clear_last_error();

const addresses = _SymbolAddresses();

class _SymbolAddresses {
  const _SymbolAddresses();
  ffi.Pointer<ffi.NativeFunction<ffi.Uint32 Function()>>
  get llama_dart_abi_version =>
      ffi.Native.addressOf(self.llama_dart_abi_version);
  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>
  get llama_dart_upstream_commit =>
      ffi.Native.addressOf(self.llama_dart_upstream_commit);
  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>
  get llama_dart_build_flags =>
      ffi.Native.addressOf(self.llama_dart_build_flags);
  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int32)>>
  get llama_dart_model_file_type_name =>
      ffi.Native.addressOf(self.llama_dart_model_file_type_name);
  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>
  get llama_dart_multimodal_marker =>
      ffi.Native.addressOf(self.llama_dart_multimodal_marker);
  ffi.Pointer<ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Uint32)>>
  get llama_dart_log_set_level =>
      ffi.Native.addressOf(self.llama_dart_log_set_level);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ffi.Uint32>,
        ffi.Pointer<llama_dart_buffer>,
      )
    >
  >
  get llama_dart_log_next => ffi.Native.addressOf(self.llama_dart_log_next);
  ffi.Pointer<ffi.NativeFunction<ffi.UnsignedInt Function()>>
  get llama_dart_backend_init =>
      ffi.Native.addressOf(self.llama_dart_backend_init);
  ffi.Pointer<ffi.NativeFunction<ffi.UnsignedInt Function()>>
  get llama_dart_backend_free =>
      ffi.Native.addressOf(self.llama_dart_backend_free);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<llama_dart_capabilities>)
    >
  >
  get llama_dart_get_capabilities =>
      ffi.Native.addressOf(self.llama_dart_get_capabilities);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model_load_config>,
        ffi.Pointer<ffi.Pointer<llama_dart_model>>,
      )
    >
  >
  get llama_dart_model_load => ffi.Native.addressOf(self.llama_dart_model_load);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_dart_model>)>
  >
  get llama_dart_model_free => ffi.Native.addressOf(self.llama_dart_model_free);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<llama_dart_model_info>,
      )
    >
  >
  get llama_dart_model_get_info =>
      ffi.Native.addressOf(self.llama_dart_model_get_info);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
        ffi.Pointer<ffi.Size>,
      )
    >
  >
  get llama_dart_model_get_description =>
      ffi.Native.addressOf(self.llama_dart_model_get_description);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >
  get llama_dart_model_metadata_count =>
      ffi.Native.addressOf(self.llama_dart_model_metadata_count);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Size,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
        ffi.Pointer<ffi.Size>,
        ffi.Pointer<ffi.Char>,
        ffi.Size,
        ffi.Pointer<ffi.Size>,
      )
    >
  >
  get llama_dart_model_metadata_get =>
      ffi.Native.addressOf(self.llama_dart_model_metadata_get);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<llama_dart_buffer>,
      )
    >
  >
  get llama_dart_model_get_chat_template =>
      ffi.Native.addressOf(self.llama_dart_model_get_chat_template);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Int32>,
        ffi.Size,
        ffi.Pointer<ffi.Size>,
        ffi.Uint8,
        ffi.Uint8,
      )
    >
  >
  get llama_dart_model_tokenize =>
      ffi.Native.addressOf(self.llama_dart_model_tokenize);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<ffi.Int32>,
        ffi.Size,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Size>,
        ffi.Uint8,
        ffi.Uint8,
      )
    >
  >
  get llama_dart_model_detokenize =>
      ffi.Native.addressOf(self.llama_dart_model_detokenize);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<llama_dart_chat_message>,
        ffi.Size,
        ffi.Uint8,
        ffi.Pointer<llama_dart_buffer>,
      )
    >
  >
  get llama_dart_model_apply_chat_template =>
      ffi.Native.addressOf(self.llama_dart_model_apply_chat_template);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<llama_dart_chat_template_capabilities>,
      )
    >
  >
  get llama_dart_model_get_chat_template_capabilities => ffi.Native.addressOf(
    self.llama_dart_model_get_chat_template_capabilities,
  );
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<llama_dart_buffer>,
      )
    >
  >
  get llama_dart_model_create_chat_plan =>
      ffi.Native.addressOf(self.llama_dart_model_create_chat_plan);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<llama_dart_buffer>,
      )
    >
  >
  get llama_dart_chat_parse_output =>
      ffi.Native.addressOf(self.llama_dart_chat_parse_output);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<llama_dart_buffer>,
      )
    >
  >
  get llama_dart_json_schema_to_grammar =>
      ffi.Native.addressOf(self.llama_dart_json_schema_to_grammar);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<llama_dart_context_config>,
        ffi.Pointer<ffi.Pointer<llama_dart_context>>,
      )
    >
  >
  get llama_dart_context_create =>
      ffi.Native.addressOf(self.llama_dart_context_create);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_dart_context>)>
  >
  get llama_dart_context_free =>
      ffi.Native.addressOf(self.llama_dart_context_free);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<llama_dart_context>)
    >
  >
  get llama_dart_context_reset =>
      ffi.Native.addressOf(self.llama_dart_context_reset);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<llama_dart_context>)
    >
  >
  get llama_dart_context_warm_up =>
      ffi.Native.addressOf(self.llama_dart_context_warm_up);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(ffi.Pointer<llama_dart_context>)
    >
  >
  get llama_dart_context_cancel =>
      ffi.Native.addressOf(self.llama_dart_context_cancel);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_context>,
        ffi.Pointer<llama_dart_context_info>,
      )
    >
  >
  get llama_dart_context_get_info =>
      ffi.Native.addressOf(self.llama_dart_context_get_info);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_context>,
        ffi.Pointer<llama_dart_buffer>,
      )
    >
  >
  get llama_dart_context_state_get =>
      ffi.Native.addressOf(self.llama_dart_context_state_get);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_context>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
      )
    >
  >
  get llama_dart_context_state_set =>
      ffi.Native.addressOf(self.llama_dart_context_state_set);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_context>,
        ffi.Uint32,
        ffi.Uint32,
        ffi.Pointer<ffi.Uint32>,
      )
    >
  >
  get llama_dart_context_shift =>
      ffi.Native.addressOf(self.llama_dart_context_shift);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_context>,
        ffi.Pointer<llama_dart_completion_config>,
        ffi.Pointer<llama_dart_buffer>,
        ffi.Pointer<llama_dart_completion_stats>,
      )
    >
  >
  get llama_dart_context_complete =>
      ffi.Native.addressOf(self.llama_dart_context_complete);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_context>,
        ffi.Pointer<llama_dart_completion_config>,
        ffi.Pointer<ffi.Pointer<llama_dart_generation>>,
      )
    >
  >
  get llama_dart_generation_start =>
      ffi.Native.addressOf(self.llama_dart_generation_start);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_generation>,
        ffi.Pointer<llama_dart_buffer>,
        ffi.Pointer<llama_dart_completion_stats>,
        ffi.Pointer<ffi.Uint8>,
      )
    >
  >
  get llama_dart_generation_next =>
      ffi.Native.addressOf(self.llama_dart_generation_next);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_dart_generation>)>
  >
  get llama_dart_generation_free =>
      ffi.Native.addressOf(self.llama_dart_generation_free);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_context>,
        ffi.Pointer<llama_dart_embedding_config>,
        ffi.Pointer<llama_dart_float_buffer>,
      )
    >
  >
  get llama_dart_context_embed =>
      ffi.Native.addressOf(self.llama_dart_context_embed);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_context>,
        ffi.Pointer<llama_dart_rerank_config>,
        ffi.Pointer<ffi.Float>,
      )
    >
  >
  get llama_dart_context_rerank =>
      ffi.Native.addressOf(self.llama_dart_context_rerank);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_model>,
        ffi.Pointer<llama_dart_lora_load_config>,
        ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>>,
      )
    >
  >
  get llama_dart_lora_load => ffi.Native.addressOf(self.llama_dart_lora_load);
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_dart_lora_adapter>)>
  >
  get llama_dart_lora_free => ffi.Native.addressOf(self.llama_dart_lora_free);
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.UnsignedInt Function(
        ffi.Pointer<llama_dart_context>,
        ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>>,
        ffi.Pointer<ffi.Float>,
        ffi.Size,
      )
    >
  >
  get llama_dart_context_set_lora_adapters =>
      ffi.Native.addressOf(self.llama_dart_context_set_lora_adapters);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Uint8>)>>
  get llama_dart_buffer_free =>
      ffi.Native.addressOf(self.llama_dart_buffer_free);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Float>)>>
  get llama_dart_float_buffer_free =>
      ffi.Native.addressOf(self.llama_dart_float_buffer_free);
  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>
  get llama_dart_last_error_message =>
      ffi.Native.addressOf(self.llama_dart_last_error_message);
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>
  get llama_dart_clear_last_error =>
      ffi.Native.addressOf(self.llama_dart_clear_last_error);
}

sealed class llama_dart_result {
  static const LLAMA_DART_SUCCESS = 0;
  static const LLAMA_DART_ERROR_INVALID_ARGUMENT = 1;
  static const LLAMA_DART_ERROR_UNSUPPORTED = 2;
  static const LLAMA_DART_ERROR_INTERNAL = 3;
  static const LLAMA_DART_ERROR_MODEL_LOAD = 4;
  static const LLAMA_DART_ERROR_BUFFER_TOO_SMALL = 5;
  static const LLAMA_DART_ERROR_CONTEXT_CREATE = 6;
  static const LLAMA_DART_ERROR_GENERATION = 7;
  static const LLAMA_DART_ERROR_EMBEDDING = 8;
  static const LLAMA_DART_ERROR_CANCELLED = 9;
  static const LLAMA_DART_ERROR_RERANKING = 10;
  static const LLAMA_DART_ERROR_LORA = 11;
}

sealed class llama_dart_capability_flags {
  static const LLAMA_DART_CAP_MODEL_LOADING = 128;
  static const LLAMA_DART_CAP_TOKENIZATION = 256;
  static const LLAMA_DART_CAP_STRUCTURED_OUTPUT = 512;
  static const LLAMA_DART_CAP_TEXT_GENERATION = 1;
  static const LLAMA_DART_CAP_EMBEDDINGS = 2;
  static const LLAMA_DART_CAP_RERANKING = 4;
  static const LLAMA_DART_CAP_MULTIMODAL = 8;
  static const LLAMA_DART_CAP_LORA = 16;
  static const LLAMA_DART_CAP_SPECULATIVE_DECODING = 32;
  static const LLAMA_DART_CAP_MTP = 64;
  static const LLAMA_DART_CAP_METAL = 1024;
  static const LLAMA_DART_CAP_VULKAN = 2048;
  static const LLAMA_DART_CAP_TOOL_CALLING = 4096;
  static const LLAMA_DART_CAP_LOGGING = 8192;
  static const LLAMA_DART_CAP_PREFILL = 16384;
}

final class llama_dart_capabilities extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint64()
  external int flags;
}

final class llama_dart_model extends ffi.Opaque {}

final class llama_dart_context extends ffi.Opaque {}

final class llama_dart_generation extends ffi.Opaque {}

final class llama_dart_lora_adapter extends ffi.Opaque {}

sealed class llama_dart_gpu_backend {
  static const LLAMA_DART_GPU_BACKEND_AUTO = 0;
  static const LLAMA_DART_GPU_BACKEND_CPU = 1;
  static const LLAMA_DART_GPU_BACKEND_METAL = 2;
  static const LLAMA_DART_GPU_BACKEND_VULKAN = 3;
}

sealed class llama_dart_log_level {
  static const LLAMA_DART_LOG_DISABLED = 0;
  static const LLAMA_DART_LOG_DEBUG = 1;
  static const LLAMA_DART_LOG_INFO = 2;
  static const LLAMA_DART_LOG_WARNING = 3;
  static const LLAMA_DART_LOG_ERROR = 4;
}

sealed class llama_dart_media_type {
  static const LLAMA_DART_MEDIA_IMAGE = 1;
  static const LLAMA_DART_MEDIA_AUDIO = 2;
}

sealed class llama_dart_speculative_type {
  static const LLAMA_DART_SPECULATIVE_NONE = 0;
  static const LLAMA_DART_SPECULATIVE_NGRAM_SIMPLE = 1;
  static const LLAMA_DART_SPECULATIVE_DRAFT_MODEL = 2;
  static const LLAMA_DART_SPECULATIVE_EAGLE3 = 3;
  static const LLAMA_DART_SPECULATIVE_MTP = 4;
  static const LLAMA_DART_SPECULATIVE_NGRAM_MAP_K = 5;
  static const LLAMA_DART_SPECULATIVE_NGRAM_MAP_K4V = 6;
  static const LLAMA_DART_SPECULATIVE_DFLASH = 7;
  static const LLAMA_DART_SPECULATIVE_NGRAM_MOD = 8;
  static const LLAMA_DART_SPECULATIVE_NGRAM_CACHE = 9;
}

sealed class llama_dart_add_special_mode {
  static const LLAMA_DART_ADD_SPECIAL_NEVER = 0;
  static const LLAMA_DART_ADD_SPECIAL_ALWAYS = 1;
  static const LLAMA_DART_ADD_SPECIAL_IF_CONTEXT_EMPTY = 2;
}

sealed class llama_dart_stop_reason {
  static const LLAMA_DART_STOP_REASON_UNKNOWN = 0;
  static const LLAMA_DART_STOP_REASON_END_OF_GENERATION = 1;
  static const LLAMA_DART_STOP_REASON_STOP_SEQUENCE = 2;
  static const LLAMA_DART_STOP_REASON_STOP_TOKEN = 3;
  static const LLAMA_DART_STOP_REASON_MAX_TOKENS = 4;
}

sealed class llama_dart_kv_cache_type {
  static const LLAMA_DART_KV_CACHE_DEFAULT = 0;
  static const LLAMA_DART_KV_CACHE_F32 = 1;
  static const LLAMA_DART_KV_CACHE_F16 = 2;
  static const LLAMA_DART_KV_CACHE_BF16 = 3;
  static const LLAMA_DART_KV_CACHE_Q8_0 = 4;
  static const LLAMA_DART_KV_CACHE_Q4_0 = 5;
  static const LLAMA_DART_KV_CACHE_Q4_1 = 6;
  static const LLAMA_DART_KV_CACHE_IQ4_NL = 7;
  static const LLAMA_DART_KV_CACHE_Q5_0 = 8;
  static const LLAMA_DART_KV_CACHE_Q5_1 = 9;
}

sealed class llama_dart_flash_attention_mode {
  static const LLAMA_DART_FLASH_ATTENTION_AUTO = 0;
  static const LLAMA_DART_FLASH_ATTENTION_DISABLED = 1;
  static const LLAMA_DART_FLASH_ATTENTION_ENABLED = 2;
}

final class llama_dart_media_input extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int type;

  external ffi.Pointer<ffi.Uint8> path_data;

  @ffi.Size()
  external int path_size;

  external ffi.Pointer<ffi.Uint8> content_data;

  @ffi.Size()
  external int content_size;
}

final class llama_dart_model_load_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> model_path_data;

  @ffi.Size()
  external int model_path_size;

  @ffi.Int32()
  external int n_gpu_layers;

  @ffi.Uint8()
  external int vocab_only;

  @ffi.Uint8()
  external int use_mmap;

  @ffi.Uint8()
  external int use_mlock;

  @ffi.Uint8()
  external int check_tensors;

  @ffi.Uint32()
  external int gpu_backend;

  external ffi.Pointer<ffi.Uint8> chat_template_data;

  @ffi.Size()
  external int chat_template_size;

  @ffi.Uint8()
  external int load_mtp;
}

final class llama_dart_model_info extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Int32()
  external int vocab_type;

  @ffi.Int32()
  external int n_vocab;

  @ffi.Int32()
  external int n_ctx_train;

  @ffi.Int32()
  external int n_embd;

  @ffi.Int32()
  external int n_embd_inp;

  @ffi.Int32()
  external int n_embd_out;

  @ffi.Int32()
  external int n_layer;

  @ffi.Int32()
  external int n_layer_nextn;

  @ffi.Int32()
  external int n_head;

  @ffi.Int32()
  external int n_head_kv;

  @ffi.Int32()
  external int ftype;

  @ffi.Uint64()
  external int size_bytes;

  @ffi.Uint64()
  external int n_params;

  @ffi.Int32()
  external int token_bos;

  @ffi.Int32()
  external int token_eos;

  @ffi.Int32()
  external int token_eot;

  @ffi.Int32()
  external int token_sep;

  @ffi.Int32()
  external int token_nl;

  @ffi.Int32()
  external int token_pad;

  @ffi.Int32()
  external int token_mask;

  @ffi.Uint8()
  external int has_encoder;

  @ffi.Uint8()
  external int has_decoder;

  @ffi.Uint8()
  external int is_recurrent;

  @ffi.Uint8()
  external int is_hybrid;

  @ffi.Uint8()
  external int is_diffusion;

  @ffi.Uint8()
  external int add_bos;

  @ffi.Uint8()
  external int add_eos;

  @ffi.Uint8()
  external int add_sep;
}

final class llama_dart_context_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int context_size;

  @ffi.Uint32()
  external int batch_size;

  @ffi.Uint32()
  external int ubatch_size;

  @ffi.Int32()
  external int threads;

  @ffi.Int32()
  external int batch_threads;

  @ffi.Uint8()
  external int embeddings;

  @ffi.Int32()
  external int pooling_type;

  @ffi.Int32()
  external int attention_type;

  @ffi.Uint32()
  external int speculative_ngram_n;

  @ffi.Uint32()
  external int speculative_ngram_m;

  external ffi.Pointer<ffi.Uint8> mmproj_path_data;

  @ffi.Size()
  external int mmproj_path_size;

  @ffi.Uint8()
  external int mmproj_use_gpu;

  @ffi.Uint32()
  external int speculative_type;

  external ffi.Pointer<ffi.Uint8> speculative_model_path_data;

  @ffi.Size()
  external int speculative_model_path_size;

  @ffi.Uint32()
  external int speculative_draft_max;

  @ffi.Uint32()
  external int kv_cache_key_type;

  @ffi.Uint32()
  external int kv_cache_value_type;

  @ffi.Uint32()
  external int flash_attention;

  @ffi.Uint8()
  external int kv_cache_offload;

  @ffi.Uint8()
  external int swa_full;

  @ffi.Uint8()
  external int kv_unified;

  @ffi.Uint32()
  external int speculative_ngram_min_draft;
}

final class llama_dart_context_info extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int context_size;

  @ffi.Uint32()
  external int sequence_context_size;

  @ffi.Uint32()
  external int batch_size;

  @ffi.Uint32()
  external int ubatch_size;

  @ffi.Uint32()
  external int max_sequences;

  @ffi.Uint8()
  external int supports_vision;

  @ffi.Uint8()
  external int supports_audio;

  @ffi.Uint32()
  external int gpu_backend;

  @ffi.Uint8()
  external int supports_context_shift;

  @ffi.Uint32()
  external int used_tokens;

  @ffi.Uint32()
  external int kv_cache_key_type;

  @ffi.Uint32()
  external int kv_cache_value_type;

  @ffi.Uint32()
  external int flash_attention;

  @ffi.Uint8()
  external int kv_cache_offload;

  @ffi.Uint8()
  external int swa_full;

  @ffi.Uint8()
  external int kv_unified;
}

final class llama_dart_chat_template_capabilities extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint8()
  external int supports_tools;

  @ffi.Uint8()
  external int supports_tool_calls;

  @ffi.Uint8()
  external int supports_parallel_tool_calls;
}

final class llama_dart_string_view extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int size;
}

final class llama_dart_completion_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> prompt_data;

  @ffi.Size()
  external int prompt_size;

  @ffi.Uint32()
  external int max_tokens;

  @ffi.Float()
  external double temperature;

  @ffi.Int32()
  external int top_k;

  @ffi.Float()
  external double top_p;

  @ffi.Float()
  external double min_p;

  @ffi.Float()
  external double typical_p;

  @ffi.Int32()
  external int penalty_last_n;

  @ffi.Float()
  external double repeat_penalty;

  @ffi.Float()
  external double frequency_penalty;

  @ffi.Float()
  external double presence_penalty;

  @ffi.Uint8()
  external int mirostat;

  @ffi.Float()
  external double mirostat_tau;

  @ffi.Float()
  external double mirostat_eta;

  external ffi.Pointer<ffi.Uint8> grammar_data;

  @ffi.Size()
  external int grammar_size;

  external ffi.Pointer<ffi.Uint8> grammar_root_data;

  @ffi.Size()
  external int grammar_root_size;

  external ffi.Pointer<llama_dart_string_view> stop_sequences;

  @ffi.Size()
  external int stop_sequence_count;

  @ffi.Uint32()
  external int seed;

  @ffi.Uint8()
  external int add_special;

  @ffi.Uint8()
  external int parse_special;

  external ffi.Pointer<llama_dart_media_input> media_inputs;

  @ffi.Size()
  external int media_input_count;

  external ffi.Pointer<ffi.Uint8> json_schema_data;

  @ffi.Size()
  external int json_schema_size;

  external ffi.Pointer<ffi.Uint8> chat_plan_data;

  @ffi.Size()
  external int chat_plan_size;

  external ffi.Pointer<ffi.Int32> stop_tokens;

  @ffi.Size()
  external int stop_token_count;
}

final class llama_dart_completion_stats extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int prompt_tokens;

  @ffi.Uint32()
  external int generated_tokens;

  @ffi.Double()
  external double prompt_eval_ms;

  @ffi.Double()
  external double decode_ms;

  @ffi.Double()
  external double total_ms;

  @ffi.Double()
  external double time_to_first_token_ms;

  @ffi.Uint32()
  external int speculative_draft_tokens;

  @ffi.Uint32()
  external int speculative_accepted_tokens;

  @ffi.Double()
  external double speculative_draft_ms;

  @ffi.Double()
  external double speculative_verify_ms;

  @ffi.Uint32()
  external int stop_reason;
}

final class llama_dart_buffer extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int size;
}

final class llama_dart_float_buffer extends ffi.Struct {
  external ffi.Pointer<ffi.Float> data;

  @ffi.Size()
  external int length;
}

final class llama_dart_embedding_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> text_data;

  @ffi.Size()
  external int text_size;

  @ffi.Uint8()
  external int add_special;

  @ffi.Uint8()
  external int parse_special;
}

final class llama_dart_rerank_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> query_data;

  @ffi.Size()
  external int query_size;

  external ffi.Pointer<ffi.Uint8> document_data;

  @ffi.Size()
  external int document_size;

  @ffi.Uint8()
  external int add_special;

  @ffi.Uint8()
  external int parse_special;
}

final class llama_dart_lora_load_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> path_data;

  @ffi.Size()
  external int path_size;
}

final class llama_dart_chat_message extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> role_data;

  @ffi.Size()
  external int role_size;

  external ffi.Pointer<ffi.Uint8> content_data;

  @ffi.Size()
  external int content_size;
}

const int LLAMA_DART_ABI_VERSION = 40;
