// Regenerate with: dart run ffigen --config ffigen.yaml

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Generated bindings for native/llama_dart_bridge/include/llama_dart.h.
class LlamaDartBridgeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LlamaDartBridgeBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LlamaDartBridgeBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int llama_dart_abi_version() {
    return _llama_dart_abi_version();
  }

  late final _llama_dart_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'llama_dart_abi_version',
      );
  late final _llama_dart_abi_version = _llama_dart_abi_versionPtr
      .asFunction<int Function()>();

  ffi.Pointer<ffi.Char> llama_dart_upstream_commit() {
    return _llama_dart_upstream_commit();
  }

  late final _llama_dart_upstream_commitPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'llama_dart_upstream_commit',
      );
  late final _llama_dart_upstream_commit = _llama_dart_upstream_commitPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> llama_dart_build_flags() {
    return _llama_dart_build_flags();
  }

  late final _llama_dart_build_flagsPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'llama_dart_build_flags',
      );
  late final _llama_dart_build_flags = _llama_dart_build_flagsPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> llama_dart_model_file_type_name(int ftype) {
    return _llama_dart_model_file_type_name(ftype);
  }

  late final _llama_dart_model_file_type_namePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int32)>>(
        'llama_dart_model_file_type_name',
      );
  late final _llama_dart_model_file_type_name =
      _llama_dart_model_file_type_namePtr
          .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  ffi.Pointer<ffi.Char> llama_dart_multimodal_marker() {
    return _llama_dart_multimodal_marker();
  }

  late final _llama_dart_multimodal_markerPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'llama_dart_multimodal_marker',
      );
  late final _llama_dart_multimodal_marker = _llama_dart_multimodal_markerPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  llama_dart_result llama_dart_log_set_level(int minimum_level) {
    return llama_dart_result.fromValue(
      _llama_dart_log_set_level(minimum_level),
    );
  }

  late final _llama_dart_log_set_levelPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Uint32)>>(
        'llama_dart_log_set_level',
      );
  late final _llama_dart_log_set_level = _llama_dart_log_set_levelPtr
      .asFunction<int Function(int)>();

  llama_dart_result llama_dart_log_next(
    ffi.Pointer<ffi.Uint32> out_level,
    ffi.Pointer<llama_dart_buffer> out_message,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_log_next(out_level, out_message),
    );
  }

  late final _llama_dart_log_nextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<ffi.Uint32>,
            ffi.Pointer<llama_dart_buffer>,
          )
        >
      >('llama_dart_log_next');
  late final _llama_dart_log_next = _llama_dart_log_nextPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Uint32>, ffi.Pointer<llama_dart_buffer>)
      >();

  llama_dart_result llama_dart_backend_init() {
    return llama_dart_result.fromValue(_llama_dart_backend_init());
  }

  late final _llama_dart_backend_initPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function()>>(
        'llama_dart_backend_init',
      );
  late final _llama_dart_backend_init = _llama_dart_backend_initPtr
      .asFunction<int Function()>();

  llama_dart_result llama_dart_backend_free() {
    return llama_dart_result.fromValue(_llama_dart_backend_free());
  }

  late final _llama_dart_backend_freePtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedInt Function()>>(
        'llama_dart_backend_free',
      );
  late final _llama_dart_backend_free = _llama_dart_backend_freePtr
      .asFunction<int Function()>();

  llama_dart_result llama_dart_get_capabilities(
    ffi.Pointer<llama_dart_capabilities> out_capabilities,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_get_capabilities(out_capabilities),
    );
  }

  late final _llama_dart_get_capabilitiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<llama_dart_capabilities>)
        >
      >('llama_dart_get_capabilities');
  late final _llama_dart_get_capabilities = _llama_dart_get_capabilitiesPtr
      .asFunction<int Function(ffi.Pointer<llama_dart_capabilities>)>();

  llama_dart_result llama_dart_model_load(
    ffi.Pointer<llama_dart_model_load_config> config,
    ffi.Pointer<ffi.Pointer<llama_dart_model>> out_model,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_load(config, out_model),
    );
  }

  late final _llama_dart_model_loadPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model_load_config>,
            ffi.Pointer<ffi.Pointer<llama_dart_model>>,
          )
        >
      >('llama_dart_model_load');
  late final _llama_dart_model_load = _llama_dart_model_loadPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_model_load_config>,
          ffi.Pointer<ffi.Pointer<llama_dart_model>>,
        )
      >();

  void llama_dart_model_free(ffi.Pointer<llama_dart_model> model) {
    return _llama_dart_model_free(model);
  }

  late final _llama_dart_model_freePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_dart_model>)>
      >('llama_dart_model_free');
  late final _llama_dart_model_free = _llama_dart_model_freePtr
      .asFunction<void Function(ffi.Pointer<llama_dart_model>)>();

  llama_dart_result llama_dart_model_get_info(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<llama_dart_model_info> out_info,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_get_info(model, out_info),
    );
  }

  late final _llama_dart_model_get_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<llama_dart_model_info>,
          )
        >
      >('llama_dart_model_get_info');
  late final _llama_dart_model_get_info = _llama_dart_model_get_infoPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_model>,
          ffi.Pointer<llama_dart_model_info>,
        )
      >();

  llama_dart_result llama_dart_model_get_description(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<ffi.Char> buffer,
    int buffer_size,
    ffi.Pointer<ffi.Size> out_size,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_get_description(model, buffer, buffer_size, out_size),
    );
  }

  late final _llama_dart_model_get_descriptionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('llama_dart_model_get_description');
  late final _llama_dart_model_get_description =
      _llama_dart_model_get_descriptionPtr
          .asFunction<
            int Function(
              ffi.Pointer<llama_dart_model>,
              ffi.Pointer<ffi.Char>,
              int,
              ffi.Pointer<ffi.Size>,
            )
          >();

  llama_dart_result llama_dart_model_metadata_count(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_metadata_count(model, out_count),
    );
  }

  late final _llama_dart_model_metadata_countPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('llama_dart_model_metadata_count');
  late final _llama_dart_model_metadata_count =
      _llama_dart_model_metadata_countPtr
          .asFunction<
            int Function(ffi.Pointer<llama_dart_model>, ffi.Pointer<ffi.Size>)
          >();

  llama_dart_result llama_dart_model_metadata_get(
    ffi.Pointer<llama_dart_model> model,
    int index,
    ffi.Pointer<ffi.Char> key_buffer,
    int key_buffer_size,
    ffi.Pointer<ffi.Size> out_key_size,
    ffi.Pointer<ffi.Char> value_buffer,
    int value_buffer_size,
    ffi.Pointer<ffi.Size> out_value_size,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_metadata_get(
        model,
        index,
        key_buffer,
        key_buffer_size,
        out_key_size,
        value_buffer,
        value_buffer_size,
        out_value_size,
      ),
    );
  }

  late final _llama_dart_model_metadata_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('llama_dart_model_metadata_get');
  late final _llama_dart_model_metadata_get = _llama_dart_model_metadata_getPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_model>,
          int,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Size>,
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Size>,
        )
      >();

  llama_dart_result llama_dart_model_get_chat_template(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<llama_dart_buffer> out_template,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_get_chat_template(model, out_template),
    );
  }

  late final _llama_dart_model_get_chat_templatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<llama_dart_buffer>,
          )
        >
      >('llama_dart_model_get_chat_template');
  late final _llama_dart_model_get_chat_template =
      _llama_dart_model_get_chat_templatePtr
          .asFunction<
            int Function(
              ffi.Pointer<llama_dart_model>,
              ffi.Pointer<llama_dart_buffer>,
            )
          >();

  llama_dart_result llama_dart_model_tokenize(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<ffi.Uint8> text_data,
    int text_size,
    ffi.Pointer<ffi.Int32> tokens,
    int tokens_capacity,
    ffi.Pointer<ffi.Size> out_token_count,
    int add_special,
    int parse_special,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_tokenize(
        model,
        text_data,
        text_size,
        tokens,
        tokens_capacity,
        out_token_count,
        add_special,
        parse_special,
      ),
    );
  }

  late final _llama_dart_model_tokenizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Int32>,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
            ffi.Uint8,
            ffi.Uint8,
          )
        >
      >('llama_dart_model_tokenize');
  late final _llama_dart_model_tokenize = _llama_dart_model_tokenizePtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_model>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Int32>,
          int,
          ffi.Pointer<ffi.Size>,
          int,
          int,
        )
      >();

  llama_dart_result llama_dart_model_detokenize(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<ffi.Int32> tokens,
    int token_count,
    ffi.Pointer<ffi.Uint8> text_data,
    int text_capacity,
    ffi.Pointer<ffi.Size> out_text_size,
    int remove_special,
    int unparse_special,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_detokenize(
        model,
        tokens,
        token_count,
        text_data,
        text_capacity,
        out_text_size,
        remove_special,
        unparse_special,
      ),
    );
  }

  late final _llama_dart_model_detokenizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<ffi.Int32>,
            ffi.Size,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Size>,
            ffi.Uint8,
            ffi.Uint8,
          )
        >
      >('llama_dart_model_detokenize');
  late final _llama_dart_model_detokenize = _llama_dart_model_detokenizePtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_model>,
          ffi.Pointer<ffi.Int32>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Size>,
          int,
          int,
        )
      >();

  llama_dart_result llama_dart_model_apply_chat_template(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<llama_dart_chat_message> messages,
    int message_count,
    int add_assistant_prompt,
    ffi.Pointer<llama_dart_buffer> out_prompt,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_apply_chat_template(
        model,
        messages,
        message_count,
        add_assistant_prompt,
        out_prompt,
      ),
    );
  }

  late final _llama_dart_model_apply_chat_templatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<llama_dart_chat_message>,
            ffi.Size,
            ffi.Uint8,
            ffi.Pointer<llama_dart_buffer>,
          )
        >
      >('llama_dart_model_apply_chat_template');
  late final _llama_dart_model_apply_chat_template =
      _llama_dart_model_apply_chat_templatePtr
          .asFunction<
            int Function(
              ffi.Pointer<llama_dart_model>,
              ffi.Pointer<llama_dart_chat_message>,
              int,
              int,
              ffi.Pointer<llama_dart_buffer>,
            )
          >();

  llama_dart_result llama_dart_model_get_chat_template_capabilities(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<llama_dart_chat_template_capabilities> out_capabilities,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_get_chat_template_capabilities(model, out_capabilities),
    );
  }

  late final _llama_dart_model_get_chat_template_capabilitiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<llama_dart_chat_template_capabilities>,
          )
        >
      >('llama_dart_model_get_chat_template_capabilities');
  late final _llama_dart_model_get_chat_template_capabilities =
      _llama_dart_model_get_chat_template_capabilitiesPtr
          .asFunction<
            int Function(
              ffi.Pointer<llama_dart_model>,
              ffi.Pointer<llama_dart_chat_template_capabilities>,
            )
          >();

  llama_dart_result llama_dart_model_create_chat_plan(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<ffi.Uint8> request_data,
    int request_size,
    ffi.Pointer<llama_dart_buffer> out_plan,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_model_create_chat_plan(
        model,
        request_data,
        request_size,
        out_plan,
      ),
    );
  }

  late final _llama_dart_model_create_chat_planPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<llama_dart_buffer>,
          )
        >
      >('llama_dart_model_create_chat_plan');
  late final _llama_dart_model_create_chat_plan =
      _llama_dart_model_create_chat_planPtr
          .asFunction<
            int Function(
              ffi.Pointer<llama_dart_model>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<llama_dart_buffer>,
            )
          >();

  llama_dart_result llama_dart_chat_parse_output(
    ffi.Pointer<ffi.Uint8> plan_data,
    int plan_size,
    ffi.Pointer<ffi.Uint8> output_data,
    int output_size,
    ffi.Pointer<llama_dart_buffer> out_message_json,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_chat_parse_output(
        plan_data,
        plan_size,
        output_data,
        output_size,
        out_message_json,
      ),
    );
  }

  late final _llama_dart_chat_parse_outputPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<llama_dart_buffer>,
          )
        >
      >('llama_dart_chat_parse_output');
  late final _llama_dart_chat_parse_output = _llama_dart_chat_parse_outputPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<llama_dart_buffer>,
        )
      >();

  llama_dart_result llama_dart_json_schema_to_grammar(
    ffi.Pointer<ffi.Uint8> schema_data,
    int schema_size,
    ffi.Pointer<llama_dart_buffer> out_grammar,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_json_schema_to_grammar(schema_data, schema_size, out_grammar),
    );
  }

  late final _llama_dart_json_schema_to_grammarPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<llama_dart_buffer>,
          )
        >
      >('llama_dart_json_schema_to_grammar');
  late final _llama_dart_json_schema_to_grammar =
      _llama_dart_json_schema_to_grammarPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<llama_dart_buffer>,
            )
          >();

  llama_dart_result llama_dart_context_create(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<llama_dart_context_config> config,
    ffi.Pointer<ffi.Pointer<llama_dart_context>> out_context,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_context_create(model, config, out_context),
    );
  }

  late final _llama_dart_context_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<llama_dart_context_config>,
            ffi.Pointer<ffi.Pointer<llama_dart_context>>,
          )
        >
      >('llama_dart_context_create');
  late final _llama_dart_context_create = _llama_dart_context_createPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_model>,
          ffi.Pointer<llama_dart_context_config>,
          ffi.Pointer<ffi.Pointer<llama_dart_context>>,
        )
      >();

  void llama_dart_context_free(ffi.Pointer<llama_dart_context> context) {
    return _llama_dart_context_free(context);
  }

  late final _llama_dart_context_freePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_dart_context>)>
      >('llama_dart_context_free');
  late final _llama_dart_context_free = _llama_dart_context_freePtr
      .asFunction<void Function(ffi.Pointer<llama_dart_context>)>();

  llama_dart_result llama_dart_context_reset(
    ffi.Pointer<llama_dart_context> context,
  ) {
    return llama_dart_result.fromValue(_llama_dart_context_reset(context));
  }

  late final _llama_dart_context_resetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<llama_dart_context>)
        >
      >('llama_dart_context_reset');
  late final _llama_dart_context_reset = _llama_dart_context_resetPtr
      .asFunction<int Function(ffi.Pointer<llama_dart_context>)>();

  llama_dart_result llama_dart_context_warm_up(
    ffi.Pointer<llama_dart_context> context,
  ) {
    return llama_dart_result.fromValue(_llama_dart_context_warm_up(context));
  }

  late final _llama_dart_context_warm_upPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<llama_dart_context>)
        >
      >('llama_dart_context_warm_up');
  late final _llama_dart_context_warm_up = _llama_dart_context_warm_upPtr
      .asFunction<int Function(ffi.Pointer<llama_dart_context>)>();

  llama_dart_result llama_dart_context_cancel(
    ffi.Pointer<llama_dart_context> context,
  ) {
    return llama_dart_result.fromValue(_llama_dart_context_cancel(context));
  }

  late final _llama_dart_context_cancelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(ffi.Pointer<llama_dart_context>)
        >
      >('llama_dart_context_cancel');
  late final _llama_dart_context_cancel = _llama_dart_context_cancelPtr
      .asFunction<int Function(ffi.Pointer<llama_dart_context>)>();

  llama_dart_result llama_dart_context_get_info(
    ffi.Pointer<llama_dart_context> context,
    ffi.Pointer<llama_dart_context_info> out_info,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_context_get_info(context, out_info),
    );
  }

  late final _llama_dart_context_get_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_context>,
            ffi.Pointer<llama_dart_context_info>,
          )
        >
      >('llama_dart_context_get_info');
  late final _llama_dart_context_get_info = _llama_dart_context_get_infoPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_context>,
          ffi.Pointer<llama_dart_context_info>,
        )
      >();

  llama_dart_result llama_dart_context_state_get(
    ffi.Pointer<llama_dart_context> context,
    ffi.Pointer<llama_dart_buffer> out_state,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_context_state_get(context, out_state),
    );
  }

  late final _llama_dart_context_state_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_context>,
            ffi.Pointer<llama_dart_buffer>,
          )
        >
      >('llama_dart_context_state_get');
  late final _llama_dart_context_state_get = _llama_dart_context_state_getPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_context>,
          ffi.Pointer<llama_dart_buffer>,
        )
      >();

  llama_dart_result llama_dart_context_state_set(
    ffi.Pointer<llama_dart_context> context,
    ffi.Pointer<ffi.Uint8> state_data,
    int state_size,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_context_state_set(context, state_data, state_size),
    );
  }

  late final _llama_dart_context_state_setPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_context>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
          )
        >
      >('llama_dart_context_state_set');
  late final _llama_dart_context_state_set = _llama_dart_context_state_setPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_context>,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  llama_dart_result llama_dart_context_shift(
    ffi.Pointer<llama_dart_context> context,
    int keep_tokens,
    int discard_tokens,
    ffi.Pointer<ffi.Uint32> out_discarded_tokens,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_context_shift(
        context,
        keep_tokens,
        discard_tokens,
        out_discarded_tokens,
      ),
    );
  }

  late final _llama_dart_context_shiftPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_context>,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('llama_dart_context_shift');
  late final _llama_dart_context_shift = _llama_dart_context_shiftPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_context>,
          int,
          int,
          ffi.Pointer<ffi.Uint32>,
        )
      >();

  llama_dart_result llama_dart_context_complete(
    ffi.Pointer<llama_dart_context> context,
    ffi.Pointer<llama_dart_completion_config> config,
    ffi.Pointer<llama_dart_buffer> out_text,
    ffi.Pointer<llama_dart_completion_stats> out_stats,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_context_complete(context, config, out_text, out_stats),
    );
  }

  late final _llama_dart_context_completePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_context>,
            ffi.Pointer<llama_dart_completion_config>,
            ffi.Pointer<llama_dart_buffer>,
            ffi.Pointer<llama_dart_completion_stats>,
          )
        >
      >('llama_dart_context_complete');
  late final _llama_dart_context_complete = _llama_dart_context_completePtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_context>,
          ffi.Pointer<llama_dart_completion_config>,
          ffi.Pointer<llama_dart_buffer>,
          ffi.Pointer<llama_dart_completion_stats>,
        )
      >();

  llama_dart_result llama_dart_generation_start(
    ffi.Pointer<llama_dart_context> context,
    ffi.Pointer<llama_dart_completion_config> config,
    ffi.Pointer<ffi.Pointer<llama_dart_generation>> out_generation,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_generation_start(context, config, out_generation),
    );
  }

  late final _llama_dart_generation_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_context>,
            ffi.Pointer<llama_dart_completion_config>,
            ffi.Pointer<ffi.Pointer<llama_dart_generation>>,
          )
        >
      >('llama_dart_generation_start');
  late final _llama_dart_generation_start = _llama_dart_generation_startPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_context>,
          ffi.Pointer<llama_dart_completion_config>,
          ffi.Pointer<ffi.Pointer<llama_dart_generation>>,
        )
      >();

  llama_dart_result llama_dart_generation_next(
    ffi.Pointer<llama_dart_generation> generation,
    ffi.Pointer<llama_dart_buffer> out_text,
    ffi.Pointer<llama_dart_completion_stats> out_stats,
    ffi.Pointer<ffi.Uint8> out_done,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_generation_next(generation, out_text, out_stats, out_done),
    );
  }

  late final _llama_dart_generation_nextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_generation>,
            ffi.Pointer<llama_dart_buffer>,
            ffi.Pointer<llama_dart_completion_stats>,
            ffi.Pointer<ffi.Uint8>,
          )
        >
      >('llama_dart_generation_next');
  late final _llama_dart_generation_next = _llama_dart_generation_nextPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_generation>,
          ffi.Pointer<llama_dart_buffer>,
          ffi.Pointer<llama_dart_completion_stats>,
          ffi.Pointer<ffi.Uint8>,
        )
      >();

  void llama_dart_generation_free(
    ffi.Pointer<llama_dart_generation> generation,
  ) {
    return _llama_dart_generation_free(generation);
  }

  late final _llama_dart_generation_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<llama_dart_generation>)
        >
      >('llama_dart_generation_free');
  late final _llama_dart_generation_free = _llama_dart_generation_freePtr
      .asFunction<void Function(ffi.Pointer<llama_dart_generation>)>();

  llama_dart_result llama_dart_context_embed(
    ffi.Pointer<llama_dart_context> context,
    ffi.Pointer<llama_dart_embedding_config> config,
    ffi.Pointer<llama_dart_float_buffer> out_embedding,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_context_embed(context, config, out_embedding),
    );
  }

  late final _llama_dart_context_embedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_context>,
            ffi.Pointer<llama_dart_embedding_config>,
            ffi.Pointer<llama_dart_float_buffer>,
          )
        >
      >('llama_dart_context_embed');
  late final _llama_dart_context_embed = _llama_dart_context_embedPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_context>,
          ffi.Pointer<llama_dart_embedding_config>,
          ffi.Pointer<llama_dart_float_buffer>,
        )
      >();

  llama_dart_result llama_dart_context_rerank(
    ffi.Pointer<llama_dart_context> context,
    ffi.Pointer<llama_dart_rerank_config> config,
    ffi.Pointer<ffi.Float> out_score,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_context_rerank(context, config, out_score),
    );
  }

  late final _llama_dart_context_rerankPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_context>,
            ffi.Pointer<llama_dart_rerank_config>,
            ffi.Pointer<ffi.Float>,
          )
        >
      >('llama_dart_context_rerank');
  late final _llama_dart_context_rerank = _llama_dart_context_rerankPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_context>,
          ffi.Pointer<llama_dart_rerank_config>,
          ffi.Pointer<ffi.Float>,
        )
      >();

  llama_dart_result llama_dart_lora_load(
    ffi.Pointer<llama_dart_model> model,
    ffi.Pointer<llama_dart_lora_load_config> config,
    ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>> out_adapter,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_lora_load(model, config, out_adapter),
    );
  }

  late final _llama_dart_lora_loadPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_model>,
            ffi.Pointer<llama_dart_lora_load_config>,
            ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>>,
          )
        >
      >('llama_dart_lora_load');
  late final _llama_dart_lora_load = _llama_dart_lora_loadPtr
      .asFunction<
        int Function(
          ffi.Pointer<llama_dart_model>,
          ffi.Pointer<llama_dart_lora_load_config>,
          ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>>,
        )
      >();

  void llama_dart_lora_free(ffi.Pointer<llama_dart_lora_adapter> adapter) {
    return _llama_dart_lora_free(adapter);
  }

  late final _llama_dart_lora_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<llama_dart_lora_adapter>)
        >
      >('llama_dart_lora_free');
  late final _llama_dart_lora_free = _llama_dart_lora_freePtr
      .asFunction<void Function(ffi.Pointer<llama_dart_lora_adapter>)>();

  llama_dart_result llama_dart_context_set_lora_adapters(
    ffi.Pointer<llama_dart_context> context,
    ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>> adapters,
    ffi.Pointer<ffi.Float> scales,
    int adapter_count,
  ) {
    return llama_dart_result.fromValue(
      _llama_dart_context_set_lora_adapters(
        context,
        adapters,
        scales,
        adapter_count,
      ),
    );
  }

  late final _llama_dart_context_set_lora_adaptersPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedInt Function(
            ffi.Pointer<llama_dart_context>,
            ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>>,
            ffi.Pointer<ffi.Float>,
            ffi.Size,
          )
        >
      >('llama_dart_context_set_lora_adapters');
  late final _llama_dart_context_set_lora_adapters =
      _llama_dart_context_set_lora_adaptersPtr
          .asFunction<
            int Function(
              ffi.Pointer<llama_dart_context>,
              ffi.Pointer<ffi.Pointer<llama_dart_lora_adapter>>,
              ffi.Pointer<ffi.Float>,
              int,
            )
          >();

  void llama_dart_buffer_free(ffi.Pointer<ffi.Uint8> data) {
    return _llama_dart_buffer_free(data);
  }

  late final _llama_dart_buffer_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Uint8>)>>(
        'llama_dart_buffer_free',
      );
  late final _llama_dart_buffer_free = _llama_dart_buffer_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Uint8>)>();

  void llama_dart_float_buffer_free(ffi.Pointer<ffi.Float> data) {
    return _llama_dart_float_buffer_free(data);
  }

  late final _llama_dart_float_buffer_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Float>)>>(
        'llama_dart_float_buffer_free',
      );
  late final _llama_dart_float_buffer_free = _llama_dart_float_buffer_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Float>)>();

  ffi.Pointer<ffi.Char> llama_dart_last_error_message() {
    return _llama_dart_last_error_message();
  }

  late final _llama_dart_last_error_messagePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'llama_dart_last_error_message',
      );
  late final _llama_dart_last_error_message = _llama_dart_last_error_messagePtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  void llama_dart_clear_last_error() {
    return _llama_dart_clear_last_error();
  }

  late final _llama_dart_clear_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        'llama_dart_clear_last_error',
      );
  late final _llama_dart_clear_last_error = _llama_dart_clear_last_errorPtr
      .asFunction<void Function()>();
}

enum llama_dart_result {
  LLAMA_DART_SUCCESS(0),
  LLAMA_DART_ERROR_INVALID_ARGUMENT(1),
  LLAMA_DART_ERROR_UNSUPPORTED(2),
  LLAMA_DART_ERROR_INTERNAL(3),
  LLAMA_DART_ERROR_MODEL_LOAD(4),
  LLAMA_DART_ERROR_BUFFER_TOO_SMALL(5),
  LLAMA_DART_ERROR_CONTEXT_CREATE(6),
  LLAMA_DART_ERROR_GENERATION(7),
  LLAMA_DART_ERROR_EMBEDDING(8),
  LLAMA_DART_ERROR_CANCELLED(9),
  LLAMA_DART_ERROR_RERANKING(10),
  LLAMA_DART_ERROR_LORA(11);

  final int value;
  const llama_dart_result(this.value);

  static llama_dart_result fromValue(int value) => switch (value) {
    0 => LLAMA_DART_SUCCESS,
    1 => LLAMA_DART_ERROR_INVALID_ARGUMENT,
    2 => LLAMA_DART_ERROR_UNSUPPORTED,
    3 => LLAMA_DART_ERROR_INTERNAL,
    4 => LLAMA_DART_ERROR_MODEL_LOAD,
    5 => LLAMA_DART_ERROR_BUFFER_TOO_SMALL,
    6 => LLAMA_DART_ERROR_CONTEXT_CREATE,
    7 => LLAMA_DART_ERROR_GENERATION,
    8 => LLAMA_DART_ERROR_EMBEDDING,
    9 => LLAMA_DART_ERROR_CANCELLED,
    10 => LLAMA_DART_ERROR_RERANKING,
    11 => LLAMA_DART_ERROR_LORA,
    _ => throw ArgumentError('Unknown value for llama_dart_result: $value'),
  };
}

enum llama_dart_capability_flags {
  LLAMA_DART_CAP_MODEL_LOADING(128),
  LLAMA_DART_CAP_TOKENIZATION(256),
  LLAMA_DART_CAP_STRUCTURED_OUTPUT(512),
  LLAMA_DART_CAP_TEXT_GENERATION(1),
  LLAMA_DART_CAP_EMBEDDINGS(2),
  LLAMA_DART_CAP_RERANKING(4),
  LLAMA_DART_CAP_MULTIMODAL(8),
  LLAMA_DART_CAP_LORA(16),
  LLAMA_DART_CAP_SPECULATIVE_DECODING(32),
  LLAMA_DART_CAP_MTP(64),
  LLAMA_DART_CAP_METAL(1024),
  LLAMA_DART_CAP_VULKAN(2048),
  LLAMA_DART_CAP_TOOL_CALLING(4096),
  LLAMA_DART_CAP_LOGGING(8192),
  LLAMA_DART_CAP_PREFILL(16384);

  final int value;
  const llama_dart_capability_flags(this.value);

  static llama_dart_capability_flags fromValue(int value) => switch (value) {
    128 => LLAMA_DART_CAP_MODEL_LOADING,
    256 => LLAMA_DART_CAP_TOKENIZATION,
    512 => LLAMA_DART_CAP_STRUCTURED_OUTPUT,
    1 => LLAMA_DART_CAP_TEXT_GENERATION,
    2 => LLAMA_DART_CAP_EMBEDDINGS,
    4 => LLAMA_DART_CAP_RERANKING,
    8 => LLAMA_DART_CAP_MULTIMODAL,
    16 => LLAMA_DART_CAP_LORA,
    32 => LLAMA_DART_CAP_SPECULATIVE_DECODING,
    64 => LLAMA_DART_CAP_MTP,
    1024 => LLAMA_DART_CAP_METAL,
    2048 => LLAMA_DART_CAP_VULKAN,
    4096 => LLAMA_DART_CAP_TOOL_CALLING,
    8192 => LLAMA_DART_CAP_LOGGING,
    16384 => LLAMA_DART_CAP_PREFILL,
    _ => throw ArgumentError(
      'Unknown value for llama_dart_capability_flags: $value',
    ),
  };
}

final class llama_dart_capabilities extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int abi_version;

  @ffi.Uint64()
  external int flags;
}

final class llama_dart_model extends ffi.Opaque {}

final class llama_dart_context extends ffi.Opaque {}

final class llama_dart_generation extends ffi.Opaque {}

final class llama_dart_lora_adapter extends ffi.Opaque {}

enum llama_dart_gpu_backend {
  LLAMA_DART_GPU_BACKEND_AUTO(0),
  LLAMA_DART_GPU_BACKEND_CPU(1),
  LLAMA_DART_GPU_BACKEND_METAL(2),
  LLAMA_DART_GPU_BACKEND_VULKAN(3);

  final int value;
  const llama_dart_gpu_backend(this.value);

  static llama_dart_gpu_backend fromValue(int value) => switch (value) {
    0 => LLAMA_DART_GPU_BACKEND_AUTO,
    1 => LLAMA_DART_GPU_BACKEND_CPU,
    2 => LLAMA_DART_GPU_BACKEND_METAL,
    3 => LLAMA_DART_GPU_BACKEND_VULKAN,
    _ => throw ArgumentError(
      'Unknown value for llama_dart_gpu_backend: $value',
    ),
  };
}

enum llama_dart_log_level {
  LLAMA_DART_LOG_DISABLED(0),
  LLAMA_DART_LOG_DEBUG(1),
  LLAMA_DART_LOG_INFO(2),
  LLAMA_DART_LOG_WARNING(3),
  LLAMA_DART_LOG_ERROR(4);

  final int value;
  const llama_dart_log_level(this.value);

  static llama_dart_log_level fromValue(int value) => switch (value) {
    0 => LLAMA_DART_LOG_DISABLED,
    1 => LLAMA_DART_LOG_DEBUG,
    2 => LLAMA_DART_LOG_INFO,
    3 => LLAMA_DART_LOG_WARNING,
    4 => LLAMA_DART_LOG_ERROR,
    _ => throw ArgumentError('Unknown value for llama_dart_log_level: $value'),
  };
}

enum llama_dart_media_type {
  LLAMA_DART_MEDIA_IMAGE(1),
  LLAMA_DART_MEDIA_AUDIO(2);

  final int value;
  const llama_dart_media_type(this.value);

  static llama_dart_media_type fromValue(int value) => switch (value) {
    1 => LLAMA_DART_MEDIA_IMAGE,
    2 => LLAMA_DART_MEDIA_AUDIO,
    _ => throw ArgumentError('Unknown value for llama_dart_media_type: $value'),
  };
}

enum llama_dart_speculative_type {
  LLAMA_DART_SPECULATIVE_NONE(0),
  LLAMA_DART_SPECULATIVE_NGRAM_SIMPLE(1),
  LLAMA_DART_SPECULATIVE_DRAFT_MODEL(2),
  LLAMA_DART_SPECULATIVE_EAGLE3(3),
  LLAMA_DART_SPECULATIVE_MTP(4),
  LLAMA_DART_SPECULATIVE_NGRAM_MAP_K(5),
  LLAMA_DART_SPECULATIVE_NGRAM_MAP_K4V(6),
  LLAMA_DART_SPECULATIVE_DFLASH(7),
  LLAMA_DART_SPECULATIVE_NGRAM_MOD(8),
  LLAMA_DART_SPECULATIVE_NGRAM_CACHE(9);

  final int value;
  const llama_dart_speculative_type(this.value);

  static llama_dart_speculative_type fromValue(int value) => switch (value) {
    0 => LLAMA_DART_SPECULATIVE_NONE,
    1 => LLAMA_DART_SPECULATIVE_NGRAM_SIMPLE,
    2 => LLAMA_DART_SPECULATIVE_DRAFT_MODEL,
    3 => LLAMA_DART_SPECULATIVE_EAGLE3,
    4 => LLAMA_DART_SPECULATIVE_MTP,
    5 => LLAMA_DART_SPECULATIVE_NGRAM_MAP_K,
    6 => LLAMA_DART_SPECULATIVE_NGRAM_MAP_K4V,
    7 => LLAMA_DART_SPECULATIVE_DFLASH,
    8 => LLAMA_DART_SPECULATIVE_NGRAM_MOD,
    9 => LLAMA_DART_SPECULATIVE_NGRAM_CACHE,
    _ => throw ArgumentError(
      'Unknown value for llama_dart_speculative_type: $value',
    ),
  };
}

enum llama_dart_add_special_mode {
  LLAMA_DART_ADD_SPECIAL_NEVER(0),
  LLAMA_DART_ADD_SPECIAL_ALWAYS(1),
  LLAMA_DART_ADD_SPECIAL_IF_CONTEXT_EMPTY(2);

  final int value;
  const llama_dart_add_special_mode(this.value);

  static llama_dart_add_special_mode fromValue(int value) => switch (value) {
    0 => LLAMA_DART_ADD_SPECIAL_NEVER,
    1 => LLAMA_DART_ADD_SPECIAL_ALWAYS,
    2 => LLAMA_DART_ADD_SPECIAL_IF_CONTEXT_EMPTY,
    _ => throw ArgumentError(
      'Unknown value for llama_dart_add_special_mode: $value',
    ),
  };
}

enum llama_dart_stop_reason {
  LLAMA_DART_STOP_REASON_UNKNOWN(0),
  LLAMA_DART_STOP_REASON_END_OF_GENERATION(1),
  LLAMA_DART_STOP_REASON_STOP_SEQUENCE(2),
  LLAMA_DART_STOP_REASON_STOP_TOKEN(3),
  LLAMA_DART_STOP_REASON_MAX_TOKENS(4);

  final int value;
  const llama_dart_stop_reason(this.value);

  static llama_dart_stop_reason fromValue(int value) => switch (value) {
    0 => LLAMA_DART_STOP_REASON_UNKNOWN,
    1 => LLAMA_DART_STOP_REASON_END_OF_GENERATION,
    2 => LLAMA_DART_STOP_REASON_STOP_SEQUENCE,
    3 => LLAMA_DART_STOP_REASON_STOP_TOKEN,
    4 => LLAMA_DART_STOP_REASON_MAX_TOKENS,
    _ => throw ArgumentError(
      'Unknown value for llama_dart_stop_reason: $value',
    ),
  };
}

enum llama_dart_kv_cache_type {
  LLAMA_DART_KV_CACHE_DEFAULT(0),
  LLAMA_DART_KV_CACHE_F32(1),
  LLAMA_DART_KV_CACHE_F16(2),
  LLAMA_DART_KV_CACHE_BF16(3),
  LLAMA_DART_KV_CACHE_Q8_0(4),
  LLAMA_DART_KV_CACHE_Q4_0(5),
  LLAMA_DART_KV_CACHE_Q4_1(6),
  LLAMA_DART_KV_CACHE_IQ4_NL(7),
  LLAMA_DART_KV_CACHE_Q5_0(8),
  LLAMA_DART_KV_CACHE_Q5_1(9);

  final int value;
  const llama_dart_kv_cache_type(this.value);

  static llama_dart_kv_cache_type fromValue(int value) => switch (value) {
    0 => LLAMA_DART_KV_CACHE_DEFAULT,
    1 => LLAMA_DART_KV_CACHE_F32,
    2 => LLAMA_DART_KV_CACHE_F16,
    3 => LLAMA_DART_KV_CACHE_BF16,
    4 => LLAMA_DART_KV_CACHE_Q8_0,
    5 => LLAMA_DART_KV_CACHE_Q4_0,
    6 => LLAMA_DART_KV_CACHE_Q4_1,
    7 => LLAMA_DART_KV_CACHE_IQ4_NL,
    8 => LLAMA_DART_KV_CACHE_Q5_0,
    9 => LLAMA_DART_KV_CACHE_Q5_1,
    _ => throw ArgumentError(
      'Unknown value for llama_dart_kv_cache_type: $value',
    ),
  };
}

enum llama_dart_flash_attention_mode {
  LLAMA_DART_FLASH_ATTENTION_AUTO(0),
  LLAMA_DART_FLASH_ATTENTION_DISABLED(1),
  LLAMA_DART_FLASH_ATTENTION_ENABLED(2);

  final int value;
  const llama_dart_flash_attention_mode(this.value);

  static llama_dart_flash_attention_mode fromValue(int value) =>
      switch (value) {
        0 => LLAMA_DART_FLASH_ATTENTION_AUTO,
        1 => LLAMA_DART_FLASH_ATTENTION_DISABLED,
        2 => LLAMA_DART_FLASH_ATTENTION_ENABLED,
        _ => throw ArgumentError(
          'Unknown value for llama_dart_flash_attention_mode: $value',
        ),
      };
}

final class llama_dart_media_input extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int type;

  external ffi.Pointer<ffi.Uint8> path_data;

  @ffi.Size()
  external int path_size;

  external ffi.Pointer<ffi.Uint8> content_data;

  @ffi.Size()
  external int content_size;
}

final class llama_dart_model_load_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> model_path_data;

  @ffi.Size()
  external int model_path_size;

  @ffi.Int32()
  external int n_gpu_layers;

  @ffi.Uint8()
  external int vocab_only;

  @ffi.Uint8()
  external int use_mmap;

  @ffi.Uint8()
  external int use_mlock;

  @ffi.Uint8()
  external int check_tensors;

  @ffi.Uint32()
  external int gpu_backend;

  external ffi.Pointer<ffi.Uint8> chat_template_data;

  @ffi.Size()
  external int chat_template_size;

  @ffi.Uint8()
  external int load_mtp;
}

final class llama_dart_model_info extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Int32()
  external int vocab_type;

  @ffi.Int32()
  external int n_vocab;

  @ffi.Int32()
  external int n_ctx_train;

  @ffi.Int32()
  external int n_embd;

  @ffi.Int32()
  external int n_embd_inp;

  @ffi.Int32()
  external int n_embd_out;

  @ffi.Int32()
  external int n_layer;

  @ffi.Int32()
  external int n_layer_nextn;

  @ffi.Int32()
  external int n_head;

  @ffi.Int32()
  external int n_head_kv;

  @ffi.Int32()
  external int ftype;

  @ffi.Uint64()
  external int size_bytes;

  @ffi.Uint64()
  external int n_params;

  @ffi.Int32()
  external int token_bos;

  @ffi.Int32()
  external int token_eos;

  @ffi.Int32()
  external int token_eot;

  @ffi.Int32()
  external int token_sep;

  @ffi.Int32()
  external int token_nl;

  @ffi.Int32()
  external int token_pad;

  @ffi.Int32()
  external int token_mask;

  @ffi.Uint8()
  external int has_encoder;

  @ffi.Uint8()
  external int has_decoder;

  @ffi.Uint8()
  external int is_recurrent;

  @ffi.Uint8()
  external int is_hybrid;

  @ffi.Uint8()
  external int is_diffusion;

  @ffi.Uint8()
  external int add_bos;

  @ffi.Uint8()
  external int add_eos;

  @ffi.Uint8()
  external int add_sep;
}

final class llama_dart_context_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int context_size;

  @ffi.Uint32()
  external int batch_size;

  @ffi.Uint32()
  external int ubatch_size;

  @ffi.Int32()
  external int threads;

  @ffi.Int32()
  external int batch_threads;

  @ffi.Uint8()
  external int embeddings;

  @ffi.Int32()
  external int pooling_type;

  @ffi.Int32()
  external int attention_type;

  @ffi.Uint32()
  external int speculative_ngram_n;

  @ffi.Uint32()
  external int speculative_ngram_m;

  external ffi.Pointer<ffi.Uint8> mmproj_path_data;

  @ffi.Size()
  external int mmproj_path_size;

  @ffi.Uint8()
  external int mmproj_use_gpu;

  @ffi.Uint32()
  external int speculative_type;

  external ffi.Pointer<ffi.Uint8> speculative_model_path_data;

  @ffi.Size()
  external int speculative_model_path_size;

  @ffi.Uint32()
  external int speculative_draft_max;

  @ffi.Uint32()
  external int kv_cache_key_type;

  @ffi.Uint32()
  external int kv_cache_value_type;

  @ffi.Uint32()
  external int flash_attention;

  @ffi.Uint8()
  external int kv_cache_offload;

  @ffi.Uint8()
  external int swa_full;

  @ffi.Uint8()
  external int kv_unified;

  @ffi.Uint32()
  external int speculative_ngram_min_draft;
}

final class llama_dart_context_info extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int context_size;

  @ffi.Uint32()
  external int sequence_context_size;

  @ffi.Uint32()
  external int batch_size;

  @ffi.Uint32()
  external int ubatch_size;

  @ffi.Uint32()
  external int max_sequences;

  @ffi.Uint8()
  external int supports_vision;

  @ffi.Uint8()
  external int supports_audio;

  @ffi.Uint32()
  external int gpu_backend;

  @ffi.Uint8()
  external int supports_context_shift;

  @ffi.Uint32()
  external int used_tokens;

  @ffi.Uint32()
  external int kv_cache_key_type;

  @ffi.Uint32()
  external int kv_cache_value_type;

  @ffi.Uint32()
  external int flash_attention;

  @ffi.Uint8()
  external int kv_cache_offload;

  @ffi.Uint8()
  external int swa_full;

  @ffi.Uint8()
  external int kv_unified;
}

final class llama_dart_chat_template_capabilities extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint8()
  external int supports_tools;

  @ffi.Uint8()
  external int supports_tool_calls;

  @ffi.Uint8()
  external int supports_parallel_tool_calls;
}

final class llama_dart_string_view extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int size;
}

final class llama_dart_completion_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> prompt_data;

  @ffi.Size()
  external int prompt_size;

  @ffi.Uint32()
  external int max_tokens;

  @ffi.Float()
  external double temperature;

  @ffi.Int32()
  external int top_k;

  @ffi.Float()
  external double top_p;

  @ffi.Float()
  external double min_p;

  @ffi.Float()
  external double typical_p;

  @ffi.Int32()
  external int penalty_last_n;

  @ffi.Float()
  external double repeat_penalty;

  @ffi.Float()
  external double frequency_penalty;

  @ffi.Float()
  external double presence_penalty;

  @ffi.Uint8()
  external int mirostat;

  @ffi.Float()
  external double mirostat_tau;

  @ffi.Float()
  external double mirostat_eta;

  external ffi.Pointer<ffi.Uint8> grammar_data;

  @ffi.Size()
  external int grammar_size;

  external ffi.Pointer<ffi.Uint8> grammar_root_data;

  @ffi.Size()
  external int grammar_root_size;

  external ffi.Pointer<llama_dart_string_view> stop_sequences;

  @ffi.Size()
  external int stop_sequence_count;

  @ffi.Uint32()
  external int seed;

  @ffi.Uint8()
  external int add_special;

  @ffi.Uint8()
  external int parse_special;

  external ffi.Pointer<llama_dart_media_input> media_inputs;

  @ffi.Size()
  external int media_input_count;

  external ffi.Pointer<ffi.Uint8> json_schema_data;

  @ffi.Size()
  external int json_schema_size;

  external ffi.Pointer<ffi.Uint8> chat_plan_data;

  @ffi.Size()
  external int chat_plan_size;

  external ffi.Pointer<ffi.Int32> stop_tokens;

  @ffi.Size()
  external int stop_token_count;
}

final class llama_dart_completion_stats extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int prompt_tokens;

  @ffi.Uint32()
  external int generated_tokens;

  @ffi.Double()
  external double prompt_eval_ms;

  @ffi.Double()
  external double decode_ms;

  @ffi.Double()
  external double total_ms;

  @ffi.Double()
  external double time_to_first_token_ms;

  @ffi.Uint32()
  external int speculative_draft_tokens;

  @ffi.Uint32()
  external int speculative_accepted_tokens;

  @ffi.Double()
  external double speculative_draft_ms;

  @ffi.Double()
  external double speculative_verify_ms;

  @ffi.Uint32()
  external int stop_reason;
}

final class llama_dart_buffer extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int size;
}

final class llama_dart_float_buffer extends ffi.Struct {
  external ffi.Pointer<ffi.Float> data;

  @ffi.Size()
  external int length;
}

final class llama_dart_embedding_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> text_data;

  @ffi.Size()
  external int text_size;

  @ffi.Uint8()
  external int add_special;

  @ffi.Uint8()
  external int parse_special;
}

final class llama_dart_rerank_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> query_data;

  @ffi.Size()
  external int query_size;

  external ffi.Pointer<ffi.Uint8> document_data;

  @ffi.Size()
  external int document_size;

  @ffi.Uint8()
  external int add_special;

  @ffi.Uint8()
  external int parse_special;
}

final class llama_dart_lora_load_config extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> path_data;

  @ffi.Size()
  external int path_size;
}

final class llama_dart_chat_message extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  external ffi.Pointer<ffi.Uint8> role_data;

  @ffi.Size()
  external int role_size;

  external ffi.Pointer<ffi.Uint8> content_data;

  @ffi.Size()
  external int content_size;
}

const int LLAMA_DART_ABI_VERSION = 40;
